version: '3'

services:
  incubusdnode0:
    container_name: incubusdnode0
    image: "nephirim/incubusdnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-incubusd.log}
    volumes:
      - ./build:/incubusd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  incubusdnode1:
    container_name: incubusdnode1
    image: "nephirim/incubusdnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-incubusd.log}
    volumes:
      - ./build:/incubusd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  incubusdnode2:
    container_name: incubusdnode2
    image: "nephirim/incubusdnode"
    environment:
      - ID=2
      - LOG=${LOG:-incubusd.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/incubusd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  incubusdnode3:
    container_name: incubusdnode3
    image: "nephirim/incubusdnode"
    environment:
      - ID=3
      - LOG=${LOG:-incubusd.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/incubusd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.168.10.0/16